#!/usr/bin/env python3

import argparse

from unit.unit import Unit


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='subparser', help="Create systemd units with love")

    create = subparsers.add_parser("create", help="Create a new systemd unit")
    create.add_argument("description", help="Describe the systemd unit", type=str)
    create.add_argument("-t", "--type", help="Service type",
                        choices=['simple', 'oneshot', 'forking', 'dbus', 'notify', 'idle'], type=str)

    create.add_argument("command", help="Command to execute", type=str)

    args = parser.parse_args()
    unit = Unit()

    if args.subparser == 'create':
        print(unit.construct(args.description, args.command))

    else:
        parser.print_help()


if __name__ == '__main__':
    main()
